
[any-economy]
	#What percentage (0-100) or what amount (pvpMoneyTransfer<0) of players money should be transferred to killer
	#Range: < 100
	pvpMoneyTransfer = 0
	#Which economy to bridge to, if any. This means Grand Economy and all mods using it will use the target mod's currency. Choices are "none", "sponge", "enderpay", "forgeessentials", and "vault". The game will crash if you choose one that is not loaded. If using Sponge, make sure you have a Sponge economy loaded. If you are using Vault, make sure you have a Vault-compatible economy loaded.
	economyBridge = "none"
	#Server locale - the client's locale takes precedence if Grand Economy for Forge is installed there.
	locale = "en_us"
	#If enabled, players will be shown a message with their account balance when they join the server.
	showBalanceOnJoin = true

[native-economy]
	#The max number of days since last login the player will be paid for. Ex. If this option is set to 5, the mod will save income for 5 days of the player being offline, to give to the player when he/she logs in.
	#Range: > 0
	maxBasicIncomeSavings = 5
	#Give each player credits daily.
	basicIncome = true
	#Currency name (max 20 char)
	currencyNameSingular = "gp"
	#Currency name (max 20 char)
	currencyNameMultiple = "gp"
	#The amount of basic income to be given to a player.
	#Range: > 0
	basicIncomeAmount = 50
	#Amount of currency given to new players when they join the server
	#Range: > 0
	startBalance = 100

